--ciração da tabela
CREATE TABLE marcos(
    id_marco number GENERATED BY DEFAULT AS IDENTITY,
    id_entrega varchar2(50) NOT NULL,
    dt_marco date NOT NULL,
    valor_tecnico number,
    valor_comercial number,
    PRIMARY KEY(id_marco)
);

--inclusão
INSERT ALL
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0001', '01-03-2022', 2, 1)
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0001', '01-09-2022', 3, 2)
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0001', '01-12-2022', 5, 5)
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0015', '01-02-2022', 1, 1)
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0015', '01-06-2022', 1, 3)
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0015', '01-07-2022', 2, 3)
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0015', '01-08-2022', 3, 3)
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0015', '01-10-2022', 4, 3)
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0015', '01-11-2022', 5, 5)
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0007', '01-05-2022', 1, 1)
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0007', '01-08-2022', 2, 2)
    INTO marcos (id_entrega, dt_marco, valor_tecnico, valor_comercial) VALUES ('E-0007', '01-12-2022', 3, 2)
SELECT * FROM dual;